title: "Design Engineer Showcase"
description: "A collection of design engineer showcases."
author: "Markiian Linynskyy"
email: "linynskiy@gmail.com"
github: "dev1lmini"

url: ""
baseurl: "/showcases"

permalink: /:slug/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
